[package]
name = "eastwind-blogger"
authors = ["Zhongdong Yang"]
description = "A Rust implementation for Eastwind Blogger"
version = "2.2.3"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/zhongdongy/docker-blogger/"
homepage = "https://github.com/zhongdongy/docker-blogger/"
include = ["/src", "/templates", "/static", "favicon.ico"]


[features]
default = ["core"]
core = []
bundled = []


[dependencies]
pulldown-cmark = { version = "0.9.2", default-features = false, features = [
  "simd",
] }
pulldown-cmark-toc = "0.1.1"
serde = { version = "1.0.152", features = ["derive", "std"] }
serde_json = { version = "1.0.93" }
serde_yaml = { version = "0.9.17" }
tera = { version = "1.17.1" }
chrono = { version = "0.4.23" }
regex = "1.7.1"
walkdir = "2.3.2"
md5 = "0.7.0"
actix-web = "4"
derive_more = "0.99.17"
actix-files = "0.6.2"
lazy_static = "1.4.0"
notify = { version = "5.1.0", default-features = false, features = ["serde"] }
tokio = { version = "1.25.0", features = ["full"] }
futures = "0.3.26"
colored = "2.0.0"
log = "0.4.17"
log4rs = "1.2.0"
quick-xml = "0.28.1"
urlencoding = "2.1.2"
pinyin = "0.9"

[lib]
name = "eastwind_blogger"


[[bin]]
name = "eastwind-blogger"
