name: Build & Push to Docker Hub

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*.*.*'

jobs:
  docker-alpine:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            dongsxyz/blogger
          tags: |
            type=raw,value=latest
            type=semver,pattern={{version}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: './Dockerfile'
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: curl
        uses: wei/curl@v1
        with:
          args: |
            -X POST "${{ secrets.FEISHU_BOT_WEBHOOK }}" -H "Content-Type: application/json" -d '{"msg_type":"text","content":{"text":"dongsxyz/blogger 已经更新"}}'